random_seed: 42
tokenization:
  vocab_size: 10000
  save_path: tokenizer.pkl
  tokenizer:
    _target_: llm.tokenization.BPETokenizer
    vocab_size: ${tokenization.vocab_size}
    special_tokens:
      - ${tokenization.training.pre_tokenization_split_token}
    pre_tokenization_regex: |-
      '(?:[sdmt]|ll|ve|re)| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+
  training:
    corpus_path: data/TinyStoriesV2-GPT4-train.txt
    num_processes: 32
    pre_tokenization_split_token: "<|endoftext|>"
model:
  embedding_dim: 512
  num_transformer_blocks: 4
  num_heads: 16
  feed_forward_dim: 1344
  rope_theta: 10000.0
  max_sequence_len: 256
  vocab_size: ${tokenization.vocab_size}
