num_steps: 7501
batch_size: 128
mixed_precision_policy: p=f32,c=bf16
checkpoints_path: /tmp/minigpt_checkpoints/
optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 1.0
    - _target_: optax.adamw
      learning_rate:
        _target_: optax.schedules.warmup_cosine_decay_schedule
        init_value: 1e-4
        peak_value: 1e-2
        warmup_steps: 500
        decay_steps: ${training.num_steps}
eval:
  every_n_steps: 2500
  batch_size: 512
  generate_text:
    prompt: ${tokenization.training.pre_tokenization_split_token}
    num_tokens: 100
